FROM nginx

RUN apt-get -y update
RUN apt-get -y install vim
RUN apt-get -y install curl

RUN mkdir meu-site
RUN cd meu-site
RUN echo index.html

#VOU UTILIZAR O MEU HTML QUE JÁ ESTÁ SENDO MANDADO
COPY static-html-directory /usr/share/nginx/html


LABEL Image="Imagem Docker do nginx para WEB" \
    Version="1.0" \
    Author="RM99433" \
    Description="Fiz uma página com keyframe em css"\ 
    E-mail="rm99433@fiap.com.br"


EXPOSE 8080